# Generated by Django 3.1.5 on 2021-01-19 17:09

from django.db import migrations, models
import do_today.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('do_today', models.BooleanField()),
                ('priority', models.IntegerField()),
                ('tag_names', do_today.models.ListField()),
                ('child_order', models.IntegerField()),
                ('responsible_uid', models.IntegerField()),
                ('assigned_by_uid', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('checked', models.BooleanField()),
                ('parent_id', models.IntegerField()),
                ('day_order', models.IntegerField()),
                ('due', models.BooleanField()),
                ('user_id', models.IntegerField()),
                ('is_deleted', models.BooleanField()),
                ('sync_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('added_by_uid', models.IntegerField()),
                ('labels', do_today.models.ListField()),
                ('project_id', models.IntegerField()),
                ('date_completed', models.DateTimeField()),
                ('in_history', models.BooleanField()),
                ('has_more_notes', models.BooleanField()),
                ('collapsed', models.BooleanField()),
                ('tags_to_add', do_today.models.ListField()),
                ('last_synched', models.DateTimeField()),
            ],
        ),
    ]
